/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wt.integration;

import com.wt.integration.customvision.CustomVisionResponse;
import com.wt.integration.customvision.CustomVisionService;
import com.wt.integration.videoindexer.VideoIndexerResponse;
import com.wt.integration.videoindexer.VideoIndexerService;

import java.io.IOException;
import java.util.List;

import static com.wt.integration.ConfigVariables.*;

public class App {

    public static void main(String[] args) throws IOException {
        String accessToken = VideoIndexerService.getAccessToken(VI_ACCOUNT_ID);
        VideoIndexerResponse videoIndexerResponse = VideoIndexerService.getIndexedVideo(accessToken, VI_ACCOUNT_ID, VI_VIDEO_ID);
        List<String> thumbnailIds = VideoIndexerService.toThumbnailIds(videoIndexerResponse);

        for (String id : thumbnailIds) {
            byte[] image = VideoIndexerService.getThumbnail(accessToken, VI_ACCOUNT_ID, VI_VIDEO_ID, id);
            CustomVisionResponse customVisionResponse = CustomVisionService.detectImage(CV_PREDICTION_KEY, CV_PROJECT_ID, CV_PUBLISHED_AS_NAME, image);
            CustomVisionService.detectEnsoLogo(customVisionResponse, id);
        }

    }
}
